### ISSUE TITLE
参数和返回值是Ljava.util.HashMap，能打印里面的内容吗？

### ISSUE THREAD

**Issue by tmxd09887** [monkeylord/XServer#12]
Args 1
Ljava.util.HashMap;#172868715=>{}

Return
Ljava.util.HashMap;#-1775299122=>{}

monitor能打印里面的内容就好了

**Comment by monkeylord** [comment]
好主意

**Comment by monkeylord** [comment]
代码已Push，试试看？

**Comment by monkeylord** [comment]
[XServer V0.7.2beta.apk.zip](https://github.com/monkeylord/XServer/files/4981966/XServer.V0.7.2beta.apk.zip)

**Comment by tmxd09887** [comment]
感谢大佬

我测试了下，打印出内容了，但是好像不是标准的json格式

比如这个参数
Args 1
Ljava.util.HashMap;#336724691=>{"Ljava.lang.String;#accept-encoding":"Ljava.util.ArrayList;#-603871616=>{\n\t\"MIN_CAPACITY_INCREMENT\":\"Ljava.lang.Integer;#12\",\n\t\"size\":\"Ljava.lang.Integer;#1\"\n}","Ljava.lang.String;#content-encoding":"Ljava.util.ArrayList;#3189113=>{\n\t\"MIN_CAPACITY_INCREMENT\":\"Ljava.lang.Integer;#12\",\n\t\"size\":\"Ljava.lang.Integer;#1\"\n}","Ljava.lang.String;#content-length":"Ljava.util.ArrayList;#1508453=>{\n\t\"MIN_CAPACITY_INCREMENT\":\"Ljava.lang.Integer;#12\",\n\t\"size\":\"Ljava.lang.Integer;#1\"\n}","Ljava.lang.String;#content-type":"Ljava.util.ArrayList;#-243285100=>{\n\t\"MIN_CAPACITY_INCREMENT\":\"Ljava.lang.Integer;#12\",\n\t\"size\":\"Ljava.lang.Integer;#1\"\n}","Ljava.lang.String;#cookie":"Ljava.util.ArrayList;#-2147238956=>{\n\t\"MIN_CAPACITY_INCREMENT\":\"Ljava.lang.Integer;#12\",\n\t\"size\":\"Ljava.lang.Integer;#1\"\n}","Ljava.lang.String;#sdk-version":"Ljava.util.ArrayList;#80=>{\n\t\"MIN_CAPACITY_INCREMENT\":\"Ljava.lang.Integer;#12\",\n\t\"size\":\"Ljava.lang.Integer;#1\"\n}","Ljava.lang.String;#user-agent":"Ljava.util.ArrayList;#-1867657303=>{\n\t\"MIN_CAPACITY_INCREMENT\":\"Ljava.lang.Integer;#12\",\n\t\"size\":\"Ljava.lang.Integer;#1\"\n}","Ljava.lang.String;#x-ss-dp":"Ljava.util.ArrayList;#1509472=>{\n\t\"MIN_CAPACITY_INCREMENT\":\"Ljava.lang.Integer;#12\",\n\t\"size\":\"Ljava.lang.Integer;#1\"\n}","Ljava.lang.String;#x-ss-stub":"Ljava.util.ArrayList;#-2009388191=>{\n\t\"MIN_CAPACITY_INCREMENT\":\"Ljava.lang.Integer;#12\",\n\t\"size\":\"Ljava.lang.Integer;#1\"\n}","Ljava.lang.String;#x-tt-store-idc":"Ljava.util.ArrayList;#92903569=>{\n\t\"MIN_CAPACITY_INCREMENT\":\"Ljava.lang.Integer;#12\",\n\t\"size\":\"Ljava.lang.Integer;#1\"\n}","Ljava.lang.String;#x-tt-store-region":"Ljava.util.ArrayList;#3429=>{\n\t\"MIN_CAPACITY_INCREMENT\":\"Ljava.lang.Integer;#12\",\n\t\"size\":\"Ljava.lang.Integer;#1\"\n}","Ljava.lang.String;#x-tt-trace-id":"Ljava.util.ArrayList;#-1215393053=>{\n\t\"MIN_CAPACITY_INCREMENT\":\"Ljava.lang.Integer;#12\",\n\t\"size\":\"Ljava.lang.Integer;#1\"\n}"}

这种多层级的最好输出成json，包含的字符串可以看到内容，包含的ArrayList类型就看不到内容了

感谢大佬

**Comment by monkeylord** [comment]
嗯，可以考虑ArrayList
BTW，这种情况可以用https://github.com/monkeylord/XposedTemplateForAS自己写一个hook
XServer的打印和实时篡改功能被我写成模板了

**Comment by tmxd09887** [comment]
恩恩，xserver强大就是查询方便，自己确实可以写

感谢大佬

**Comment by monkeylord** [comment]
OK，试试这个
[XServer V0.7.2beta2.apk.zip](https://github.com/monkeylord/XServer/files/4993503/XServer.V0.7.2beta2.apk.zip)

**Comment by tmxd09887** [comment]
可以打印arrayList了
