### ISSUE TITLE
打开http://127.0.0.1:8000/没有界面

### ISSUE THREAD

**Issue by azui007** [monkeylord/XServer#5]
通过usb连接的手机，打开 http://127.0.0.1:8000/   显示
![微信图片_20190527133728](https://user-images.githubusercontent.com/9415011/58397729-d5a66100-8084-11e9-89c7-a9befe608283.png)

**Comment by monkeylord** [comment]
什么手机和系统版本呢？不确定最新的安全策略如何。
这个有可能是XServer无法在目标应用中访问自己的资源。

要不试试看模拟器？安卓逍遥模拟器非常好用。
我测试都用这个。
